<?php
namespace App\Models;
class Dispatch extends \App\Models\Base{
    protected $table = 'dispatches';

    public function raw($sql=null)
    {
        $sql ="select * from  view_dispatches";
        return parent::raw($sql); // TODO: Change the autogenerated stub
    }
}
