<?php
namespace App\Models;

class Maintenance extends Base{
    protected $table = 'maintenances';

    public function raw($sql = null):array
    {
        $sql = "select * from view_maintenance order by id desc";

        return parent::raw($sql); // TODO: Change the autogenerated stub
    }

   public function send($deviceId, $columns, $values){
        $device = parent::find('deviceId', $deviceId);
        if($device){
            $isDone = 0;
            foreach ($device as $data){
                $isDone = $data['isDone'];
            }

            if($isDone != 1){
                return json_encode(['success'=>false, 'message'=>'device exist already']);
            }

        }
       return parent::store($columns, $values);
   }

    public function markDone($maintenanceId){
        return parent::update($maintenanceId, ['isDone'], [1]);
    }


}
