<?php
namespace App\models;

class Maintenance extends Base{
    protected $table = 'maintenances';

    public function raw($sql = null)
    {
        $sql = "select * from view_maintenance order by id desc";
        return parent::raw($sql); // TODO: Change the autogenerated stub
    }


}
